package org.open2jam.gui;

import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import org.open2jam.AppContext;
import org.open2jam.Open2jam;
import org.open2jam.gui.parts.AdvancedOptions;
import org.open2jam.gui.parts.Configuration;
import org.open2jam.gui.parts.MusicSelection;


/**
 *
 * @author CdK
 */
public class Interface extends javax.swing.JFrame implements WindowListener
{

    private MusicSelection musicSelection;
    private final AppContext context;  // NEW: Store AppContext

    /** Creates new form Interface */
    public Interface(AppContext context) {  // UPDATED: Accept AppContext
        this.context = context;
        initComponents();
        setTitle(Open2jam.getProductTitle() + " - " + getTitle());

        this.setLocationRelativeTo(null);

        // Pass context to all panels
        musicSelection = new MusicSelection(context);
        Tabs.addTab("Music Selection", musicSelection);
        Tabs.addTab("Configuration", new Configuration(context));
        Tabs.addTab("Advanced Options", new AdvancedOptions(context));

        this.addWindowListener(this);
	pack();
    }
    
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tabs = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Music Select");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Tabs, javax.swing.GroupLayout.DEFAULT_SIZE, 928, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Tabs, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
        );

        Tabs.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Tabs;
    // End of variables declaration//GEN-END:variables

    @Override
    public void windowOpened(WindowEvent we) {
        
    }

    @Override
    public void windowClosing(WindowEvent we) {
        // Signal any running game to stop
        if (musicSelection != null) {
            musicSelection.windowClosing();
        }
        // Don't wait - shutdown hook handles cleanup
    }

    @Override
    public void windowClosed(WindowEvent we) {
        // Ensure JVM exits cleanly
        System.exit(0);
    }

    @Override
    public void windowIconified(WindowEvent we) {
        
    }

    @Override
    public void windowDeiconified(WindowEvent we) {
        
    }

    @Override
    public void windowActivated(WindowEvent we) {
        
    }

    @Override
    public void windowDeactivated(WindowEvent we) {
        
    }
}
